name: Automated Workflow FinancialGoalManager

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest
                            
    env:
      Solution_Name: FinancialGoalManager.sln
      Test_Project_Path: FinancialGoalManager.Tests/FinancialGoalManager.Tests.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add MSBuild to the PATH
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test ${{ env.Test_Project_Path }} --configuration ${{ matrix.configuration }}

    # Restore and build the solution
    - name: Restore and build the application
      run: |
        dotnet restore ${{ env.Solution_Name }}
        dotnet build ${{ env.Solution_Name }} --configuration ${{ matrix.configuration }} --no-restore

    # Upload build artifacts (opcional, dependendo dos arquivos que você quer armazenar)
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Build Outputs
        path: bin/Release/net7.0
